feat: update substrate sdk version to polkadot v1.9
perun-network/perun-polkadot-pallet pull request #24
Opened 2024-04-22 07:35 UTC by NhoxxKienn

This pull request updates the Substrate SDK version to Polkadot v1.9. By incorporating the latest Polkadot release (v1.9)

As reference: https://github.com/substrate-developer-hub/substrate-node-template

Changes made:
- Update dependencies in `Cargo.toml`
- Remove outdated interfaces `Default` for PK and add interface `TypeInfo` requirement in `types.rs`
- Change required attributes in `src/lib.rs` (ex: `Event` to `RuntimeEvent` + add `#[pallet::without_storage_info]` for struct to specified unknown `MaxEncodedLen` parameters, add explicit call_index for each call).
- Change `weight.rs` conversion from int to fit the new Weight package
- In `test`, change expected error from `InsufficientBalance` to `FundsUnvailabe` for the case insufficient depositing.

**Important**: This PR must be reviewed first before reviewing the PR from Perun-Polkadot-Node because the Node uses a submodule of pallet inside.

2024-04-22 14:00 UTC, DragonDev1906 requested changes

2024-04-23 09:02 UTC, NhoxxKienn commented on tests/unit.rs
> +			};
Solved by [[0fd4c06](https://github.com/perun-network/perun-polkadot-pallet/pull/24/commits/0fd4c062f1f60f95bb3e83428a36fb09c9272bce)

2024-04-23 09:02 UTC, NhoxxKienn commented on Cargo.toml
> +syn = "=1.0.109"
Solved by [0fd4c06](https://github.com/perun-network/perun-polkadot-pallet/pull/24/commits/0fd4c062f1f60f95bb3e83428a36fb09c9272bce)

2024-04-23 10:22 UTC, DragonDev1906 approved these changes

2024-04-25 07:13 UTC, merged